### ISSUE TITLE
Setup local development environment for MLS

### ISSUE THREAD

**Issue by ccooper** [taskcluster/scrum#16]
Everyone on the Service Engineering team should have a functional development environment for MLS. The setup instructions are here: https://ichnaea.readthedocs.io/en/latest/local_dev.html

1 story point per person X 5 = 5 story points total

**Comment by ccooper** [comment]
Each of us should leave a comment once we have our dev environment setup, then we can close this out.

**Comment by djmitche** [comment]
https://github.com/mozilla/ichnaea/pull/1314

**Comment by helfi92** [comment]
done

**Comment by ccooper** [comment]
I'm done too.

**Comment by petemoore** [comment]
Done.

**Comment by imbstack** [comment]
```
============================== 874 passed in 32.21s ==============================
```

Done!
