### ISSUE TITLE
Determine required cost/usage reporting for object service

### ISSUE THREAD

**Issue by djmitche** [taskcluster/scrum#40]
We have historically done a poor job of providing data on costs associated with Taskcluster.  For the object service, let's get out in front of that.

At completion of this epic, we have a document describing the information that deployers and administrators will get regarding usage and costs associated with the object service.  This should include precise definitions of that information (what is and is not included) and a proposal for how to calculate it as part of the operation of the object service across storage backends.  #39 covers implementation.

**Comment by djmitche** [comment]
We can start this work straight from the epic issue, breaking down into sub-issues if concrete bits emerge.

**Comment by djmitche** [comment]
(I broke this out into a sub-task, for tracking)

**Comment by ccooper** [comment]
@djmitche can we close out this epic now?

**Comment by djmitche** [comment]
Inded.
