### ISSUE TITLE
 Investigate feasibility of GCP marketplace taskcluster offering

### ISSUE THREAD

**Issue by ccooper** [taskcluster/scrum#53]
Functionally cloned from #43.

It may be possible to offer Taskcluster as a service via the GCP marketplace to arbitrary GCP users. At the moment we don't know much about the mechanics of the GCP marketplace, so this epic is to perform a feasibility study, prior to any actual implementation. The goal of this epic is to have an understanding of the amount of work that would be involved in order to offer Taskcluster as a service, how the offering would look to users, how it could be marketed inside GCP, and to have an overview of how the financing works, should Mozilla choose to offer it as a paid service.

https://console.cloud.google.com/marketplace

**Comment by djmitche** [comment]
I think we determined that this was infeasible at the time, and certainly now.
