### ISSUE TITLE
Reorganize issue-triage process

### ISSUE THREAD

**Issue by djmitche** [taskcluster/scrum#54]
https://github.com/taskcluster/scrum/#workspace-configuration says (to paraphrase) that new issues should go to "New Issues", while "Icebox" is a place to hold issue that are probably WONTFIX.

However, ZenHub puts new issues in "Icebox", and we've triaged most of our probably-WONTFIX bugs into "New Issues".

It seems like these names are just reversed.  The ZenHub docs are unclear, but I suspect it just dumps newly-discovered issues (those filed on GitHub) into the first pipeline in the workspace.

So, I propose:
 * move the existing mozilla/ichnaea issues into "New Issues" (WONTFIX) or "Product Backlog" (WILLFIX) depending on their disposition
 * swap the names of "Icebox" and "New Issues" so that "New Issues" is the first pipeline, and so that all of our probably-WONTFIX issues are in "Icebox"

@jwhitlock & @ccooper what do you think?

**Comment by ccooper** [comment]
>     * move the existing mozilla/ichnaea issues into "New Issues" (WONTFIX) or "Product Backlog" (WILLFIX) depending on their disposition
> 
>     * swap the names of "Icebox" and "New Issues" so that "New Issues" is the first pipeline, and so that all of our probably-WONTFIX issues are in "Icebox"

WFM

**Comment by ccooper** [comment]
...and done.
